### ISSUE TITLE
kuka-serverless tests failing

### ISSUE THREAD

**Issue by nake89** [kuka-js/kuka#165]
They used to work with spinning up a serverless-offline in the CI. Flat out not working anymore. Tried to fix it in a couple of ways already.
This does not seem like stable solution. I might genuinely just deploy to AWS Lambda dev on CI and then test against that dev.
There have been some articles making arguments for testing against actual AWS Lambda and not serverless-offline.

**Comment by nake89** [comment]
Still fixing this. CI still failing. But basically got everything to work. I'm just deploying straight to Lambda to run CI tests. Some tests failed, because the table already existed and had some entries. Gotta make it `if CI then create and read from table with -ci -prefix or something`.

**Comment by nake89** [comment]
https://www.serverless.com/dynamodb#dynamodb-with-serverless-framework
https://www.serverless.com/framework/docs/providers/aws/guide/resources/#configuration

**Comment by nake89** [comment]
Can only add one GSI to cloudformation: https://cloudkatha.com/solved-cannot-perform-more-than-one-gsi-creation-or-deletion-in-a-single-update/

**Comment by nake89** [comment]
Solution:
Put one GSI in serverless.yaml.
Deploy.
Then add second GSI through API.
Upon success, run tests.
Delete table through API. (Have to delete table even if tests fail... If tests fail CI quits? Risk that table stays? Maybe make lambda that checks for table every X minutes and deletes if exists.)

**Comment by nake89** [comment]
https://stackoverflow.com/questions/36918408/unable-to-add-gsi-to-dynamodb-table-using-cloudformation
Cloudformation appears to be useless for this.

Do it programatically: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/getting-started-step-6.html
I think this is the method to call in the SDK: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#updateTable-property

**Comment by nake89** [comment]
Thinking of something like this to create the table and first GSI:
```
resources: # CloudFormation template syntax
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}-${env:STAGE}
        AttributeDefinitions:
          - AttributeName: "PK"
            AttributeType: S
          - AttributeName: "SK"
            AttributeType: S
        KeySchema:
          - AttributeName: "PK"
            KeyType: "HASH"
          - AttributeName: "SK"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
            IndexName: "sk-pk-index"
            KeySchema:
              - AttributeName: "SK"
                KeyType: "HASH"
              - AttributeName: "PK"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
```
